name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      env: 
        PROD_URL: ${{ secrets.PROD_URL }}
        PROD_LOGIN: ${{ secrets.PROD_LOGIN }}
        PROD_PASSWORD: ${{ secrets.PROD_PASSWORD }}
      - uses: ./.github/actions/clio-pushw
        with: 
          url: $PROD_URL
          login: $PROD_LOGIN
          password: $PROD_PASSWORD