name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    env:
      URL: ${{ secrets.PROD_URL }}
      LOGIN: ${{ secrets.PROD_LOGIN }}
      PASSWORD: ${{ secrets.PROD_PASSWORD }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Push to destination
        uses: ./.github/actions/clio-pushw
        with: 
          url: $URL
          login: $LOGIN
          password: $PASSWORD