name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/clio-pushw
        env: 
          PROD_URL: ${{ secrets.PROD_URL }}
          PROD_LOGIN: ${{ secrets.PROD_LOGIN }}
          PROD_PASSWORD: ${{ secrets.PROD_PASSWORD }}
        with: 
          url: PROD_URL
          login: PROD_LOGIN
          password: PROD_PASSWORD